replicaCount: 3

image:
  repository: go-app
  tag: v1.0.0
  pullPolicy: IfNotPresent

config:
  appEnv: "production-gitops"
  forceUnready: "false"

secret:
  dbUser: "gitops_prod_admin"
  dbPass: "SuperSecretGitOpsProdPass2026!"

storage:
  enabled: true
  storageClass: local-path
  size: 2Gi

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
