apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-app-pvc
  namespace: mini-prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
