apiVersion: v1
kind: Secret
metadata:
  name: {{ include "go-app.fullname" . }}-secret
  labels:
    {{- include "go-app.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.secret.dbUser | b64enc | quote }}
  DB_PASS: {{ .Values.secret.dbPass | b64enc | quote }}
