apiVersion: v1
kind: Service
metadata:
  name: {{ include "go-app.fullname" . }}
  labels:
    {{- include "go-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "go-app.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.config.port | int }}
      targetPort: {{ .Values.config.port | int }}
      protocol: TCP
