{
 "title": "Mini Prod - Cluster & App Metrics",
 "tags": [
  "kubernetes",
  "metrics",
  "mini-prod"
 ],
 "panels": [
  {
   "title": "Go App HTTP Request Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{method}} {{status}}" }
   ]
  },
  {
   "title": "Pod Restarts Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=\"mini-prod\"})",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "CPU Usage Spike (millicores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"mini-prod\"}[1m])) * 1000",
     "legendFormat": "CPU Usage (m)"
    }
   ]
  }
 ]
}