apiVersion: apps/v1
kind: Deployment
metadata:
  name: mimir
  namespace: mini-prod
  labels:
    app: mimir
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mimir
  template:
    metadata:
      labels:
        app: mimir
    spec:
      containers:
      - name: mimir
        image: grafana/mimir:2.11.0
        args:
        - "-target=all"
        - "-config.file=/etc/mimir/mimir.yaml"
        ports:
        - containerPort: 9009
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 300m
            memory: 256Mi
        volumeMounts:
        - name: mimir-config
          mountPath: /etc/mimir
      volumes:
      - name: mimir-config
        configMap:
          name: mimir-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mimir-config
  namespace: mini-prod
data:
  mimir.yaml: |
    multitenancy_enabled: false
    blocks_storage:
      backend: filesystem
      filesystem:
        dir: /tmp/mimir/blocks
---
apiVersion: v1
kind: Service
metadata:
  name: mimir-service
  namespace: mini-prod
spec:
  type: ClusterIP
  selector:
    app: mimir
  ports:
  - port: 9009
    targetPort: 9009
    name: http
