apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-loki-datasource
  namespace: mini-prod
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
    - name: Mimir-Prometheus
      type: prometheus
      access: proxy
      url: http://mimir-service.mini-prod.svc:9009/prometheus
      isDefault: true
    - name: Grafana-Loki
      type: loki
      access: proxy
      url: http://loki-service.mini-prod.svc:3100
