apiVersion: apps/v1
kind: Deployment
metadata:
  name: private-app
  namespace: insiden-lab
  labels:
    app: private-app
    lab: insiden-4b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: private-app
  template:
    metadata:
      labels:
        app: private-app
    spec:
      containers:
      - name: app
        # Private registry tapi tidak ada imagePullSecrets
        image: ghcr.io/perusahaan-rahasia/secret-app:v1.0.0
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
